matrix:
  include:
    - env: NAME='fluentd - generate_throttle_configs test'
      language: ruby
      rvm:
      - 2.0
      before_script:
        cd fluentd/lib/generate_throttle_configs
      script:
        rake test

