apiVersion: "marketplace.redhat.com/v1alpha1"
kind: "CatalogSourceConfig"
metadata:
  name: "cluster-logging"
  namespace: "openshift-marketplace"
spec:
  targetNamespace: "openshift-logging"
  packages: "cluster-logging"
