apiVersion: "marketplace.redhat.com/v1alpha1"
kind: "CatalogSourceConfig"
metadata:
  name: "elasticsearch"
  namespace: "openshift-marketplace"
spec:
  targetNamespace: "openshift-operators"
  packages: "elasticsearch-operator"
